version: '3.7'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    command: 'yarn serve'
    environment: 
      - CHOKIDAR_USEPOLLING=true # <-- this enables the hot reloading
